fix: email export of data
DigitalNutritionalAssessment/gibsonify pull request #17
Opened 2022-01-09 13:00 UTC by adam-sroka

This PR aims to fix #16, the email export of data button not working on some phones.

2022-01-09 13:01 UTC, adam-sroka commented
@sshazril I just tested it with the new package, but it still doesn't work. We can leave this as it was before for now, and if no one else experiences this, then we could close it, as in the future we will anyways implement a new way of exporting data.

2022-02-03 14:15 UTC, adam-sroka commented
As mentioned in PR #21:

Upon updating the Flutter SDK, the following warnings pop up when building for Android:
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/45038919/152006953-49a4ec5b-1212-4d9d-a7c1-2d330048766b.png">
```
Note: /usr/local/Caskroom/flutter/2.5.0/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_android-2.0.11/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /usr/local/Caskroom/flutter/2.5.0/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_mailer-2.0.1/android/src/main/java/com/dataxad/flutter_mailer/FlutterMailerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Since these are related to `path_provider` and `flutter_mailer`, I suggest this PR should also involve investigating moving away from them, into something like [share_plus](https://pub.dev/packages/share_plus).

2022-02-17 06:38 UTC, adam-sroka commented
@sshazril let me know if this works for you — it does for me (finally!) and I can export the data to my email app or any other app as well.

2022-02-17 12:47 UTC, sshazril requested changes
![Screenshot_20220217-123932_Gmail](https://user-images.githubusercontent.com/63778652/154483838-1064b9df-7b78-4b96-9ca2-6cec5bf7a42c.jpg)
Looks like something breaks somewhere. It works for me mostly and sometimes it does not.
I haven't figured out exactly how to reproduce the bug but during my testing I manage to get the error at least 4 times. The bug seems to be related to making changes to collection and then saving.

2022-02-17 15:06 UTC, adam-sroka commented
> ![Screenshot_20220217-123932_Gmail](https://user-images.githubusercontent.com/63778652/154483838-1064b9df-7b78-4b96-9ca2-6cec5bf7a42c.jpg) Looks like something breaks somewhere. It works for me mostly and sometimes it does not. I haven't figured out exactly how to reproduce the bug but during my testing I manage to get the error at least 4 times. The bug seems to be related to making changes to collection and then saving.

Good catch, I'll try to reproduce and look into it.

2022-02-17 16:17 UTC, adam-sroka commented on lib/home/widgets/sync_screen.dart
> +                await Share.shareFiles([_recipefilePath, _collectionfilePath]);
You're right, just implemented it 🙌.

2022-02-20 23:23 UTC, adam-sroka commented
Hey @sshazril, I couldn't reproduce the bug — so I added a button to save to a local file as well. Hopefully this will work and we can merge this now — if the testing reveals problems, we can reopen this in the future. Let me know what you think 😊.

2022-02-21 13:47 UTC, sshazril approved these changes
Minor tweak but otherwise all good! Like the download button :)

2022-02-21 13:47 UTC, sshazril commented on lib/home/widgets/sync_screen.dart
> +      'string. <br> Data can be pasted into '
I don't think the share plugin has HTML support so can just drop the `<br>`

2022-02-21 14:45 UTC, merged